// <auto-generated />
namespace MVC2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course));
        
        string IMigrationMetadata.Id
        {
            get { return "201511070304520_-Course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
