// <auto-generated />
namespace MVC2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class recheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201511071231028_recheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
